# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

name: Gimo Song
title: Software Developer
email: goodmoskito@gmail.com
phone: 이메일로 문의 부탁 드립니다.
website: https://github.com/songgimo

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  songgimo
linkedin_username: gimosong

about_profile_image: images/gm.jpg


about_title: About Me

about_content: |
    # 안녕하세요, <br> 개발자 송기모입니다. <br>
  
content:
  - title: Summary
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## 서울에서 4년차 개발 엔지니어로 일하고 있으며 백엔드 개발 및 웹개발을 하고 있습니다. Python, Django, Linux, AWS, MariaDB, Git 등으로 웹 프로덕션 서비스를 설계 및 개발한 경험과 외주로부터 Queue, Stack, Tree등의 자료구조를 적용하고 개발한 경험이 있습니다. 
      ## 코드의 확장과 유지보수가 수월한 백엔드 구조와 패턴에 대해 고민하고, 개발하고자 하며 대부분의 프로젝트에서 기획 단계부터 릴리즈까지의 단계에 참여해 제품 개발 사이클에 대한 이해가 있습니다.
      ## 서비스 개발은 비단 코드를 잘 짜는 것 뿐만 아닌 기획과 도메인의 목적에 맞는 코드를 설계하고 개발해야 한다고 믿습니다.
      <br>
      ## 그렇기에 더 좋은 개발자로서 발전하기 위해 적극적인 커뮤니케이션으로 기획과 목적을 오해없이 동기화하고 코드에 녹여내고자 노력하고 있습니다.
      
  - title: Skill Highlights
    layout: text
    content: | # this will include new lines to allow paragraphs
      <ul class="highlights">
      <li>Python</li>
      <li>Django</li>
      <li>Git</li>
      <li>Linux</li>
      <li>MySQL</li>
      <li>MariaDB</li>
      <li>NextJS</li>
      <li>Redis</li>
      <li>Celery</li>
      <li>Threading</li>
      <li>MultiProcessing</li>
      <li>AsyncIO</li>
      <li>AWS EC2</li>
      <li>AWS RDS</li>
      <li>AWS OpenSearch</li>
      <li>HTML</li>
      <li>jQuery</li>
      <li>CSS</li>
      </ul>

  - title: Work Experience
    layout: list
    content:
      - layout: left-top
        title: 위시켓
        sub_title: Software Developer
        caption: 2019.02 -
        link: wishket.com
        description: | # this will include new lines to allow paragraphs Description of role
          <div class="custom-title">Description.</div>
          2019년부터 위시켓에 근무하면서 각종 웹 개발을 포함하여 다양한 기능을 설계 및 개발하며 유지보수하고 있습니다.
          
          <div class="custom-title">FootPrint.</div>
          - 내부 어드민 개선 및 레거시 제거
          - 회사가 요구하는 MVP 개발
          - 기존 비즈니스 로직에 대한 유지보수
          - 개발팀 DevOps 구축 및 개선
          - 내부 도메인 서비스 개선 및 유지보수
          - 리뷰 도메인 설계 및 개발
          - 스마트매칭 도메인 설계 및 개발
          - 요즘IT 검색 알고리즘 개선
          - 스마트매칭 매칭 알고리즘 개발
          
          <div class="custom-title">Tech Stack.</div>
          <mark>Python</mark>
          <mark>Django</mark> 
          <mark>jQuery</mark>
          <mark>NextJS</mark>
          <mark>Redis</mark>
          <mark>Celery</mark>
          <mark>RESTFUL</mark>
          <mark>MariaDB</mark>
  - title: Other Experience
    layout: list
    content:
      - layout: left-top
        border: weak
        title: 프리랜서 활동
        sub_title: Software Developer
        caption: 2017.02 - 2019.01
        description: | # 
          <div class="custom-title">Description.</div>
          2017년부터 사이버사령부 동기 한명과 함께 프리랜서 활동을 하며 다양한 스택으로 개발을 진행했습니다.
          <div class="custom-title">FootPrint.</div>
          - 업비트 알고리즘 거래 시스템 개발
          - 키움증권 시세추종 프로그램 개발
          - DB운용 서비스 개발 및 유지보수
          - 기타 데이터 수집 자동화 앱 개발
          
          <div class="custom-title">Tech Stack.</div>
          <mark>Python</mark>
          <mark>MySQL</mark>
          <mark>MongoDB</mark>
          <mark>AsyncIO</mark>
          <mark>SQLite</mark>
          <mark>PHP</mark>
          <mark>RESTFUL</mark>
          <mark>QT</mark>
          <mark>Selenium</mark>
      - layout: left-top
        border: weak
        title: 팀 프로젝트 활동
        sub_title: Software Developer
        caption: 2017.02 -
        description: | # 
          <div class="custom-title">Description.</div>
          2017년부터 사이버사령부 동기 두명과 함께 개인적인 프로젝트 활동을 진행했으며, Async, Threading 등 다양한 스택을 사용해 프로그램을 설계 및 개발했습니다.
          <div class="custom-title">FootPrint.</div>
          - 업비트, 빗썸, 바이낸스 3개 거래소 API, Websocket 연동
          - 거래소 간 코인 가격 차이를 이용한 재정거래 시스템 개발
          - MSI, CCI, Stochastic 등 N개의 지표를 조합하고 거래하는 시스템 개발
          - 키움증권 알고리즘 거래 시스템 개발
          
          <div class="custom-title">Tech Stack.</div>
          <mark>Python</mark> 
          <mark>MySQL</mark>
          <mark>Flask</mark>
          <mark>QT</mark>
          <mark>AsyncIO</mark>
          <mark>Threading</mark>
          <mark>Processing</mark>

      - layout: left-top
        title: 사이버사령부
        sub_title: 정보보호병
        caption: 2015.07 - 2017.02
        description: | #
          <div class="custom-title">Description.</div>
          사이버사령부에 정보보호병으로 근무했으며, 전반적으로 서버관리 및 운영 및 업무를 했으며 필요시 Python, Sh 스크립트 작성을 진행했습니다.
          <div class="custom-title">FootPrint.</div>
          - 서버 관리 및 운영
          - 암호 변경 스크립트 및 서버 상태 확인 스크립트 등 작성
          
          <div class="custom-title">Tech Stack.</div>
          <mark>Python</mark>
          <mark>Linux</mark>

  - title: Projects
    layout: list
    border: weak
    content:
      - layout: left-top
        title: 요즘IT 검색 알고리즘 개선
        border: weak
        sub_title: Software Developer
        caption: 2022.08 - 2022.10
        description: |
          <div class="custom-title">Description.</div>
          요즘IT의 검색기능이 제한적이고 정확한 컨텐츠를 검색하지 못하는 배경에서 시작한 프로젝트입니다.
          AWS OpenSearch의 서버를 구축하고 위시켓DB를 연동했으며 검색 알고리즘을 설계하고 개발했습니다.
          속도 및 정확도가 개선되었고, 기획에서 요구하던 특정 문자열을 Split하여 검색어 조합이 가능하게 했습니다.
          <div class="custom-title">FootPrint.</div>
          - 기존 Django ORM 기반 검색을 OpenSearch로 개선
          - 검색어 인덱스 기반으로 일치율 높은 결과 값을 우선하게 개선
          - 검색어 조합이 가능하게 개선
          <div class="custom-title">Tech Stack.</div>
          <mark>RESTFUL</mark>
          <mark>Redis</mark>
          <mark>Celery</mark>
          <mark>OpenSearch</mark>

      - layout: left-top
        title: 요즘IT 슬랙봇 구독 서비스 설계 및 개발
        border: weak
        sub_title: Software Developer
        caption: 2022.05 - 2022.08
        description: |
          <div class="custom-title">Description.</div>
          슬랙봇 구독 서비스를 통해 유저에게 발행된 컨텐츠를 바로 안내하고 페이지로 후킹하기 위해 시작된 프로젝트입니다.
          슬랙 Message API로 슬랙과 연동했고, Threading, Redis를 이용해 오버헤드 없이 컨텐츠를 받아볼 수 있게 처리했습니다.
          <div class="custom-title">FootPrint.</div>
          - 슬랙봇 연동 로직 개발로 슬랙봇 구독 유도
          - 유저가 외부에서 바로 컨텐츠를 유입할 수 있도록 개선
          - Threading, Redis를 이용해 오버헤드 없이 컨텐츠를 바로 Delivery할 수 있게 처리
          <div class="custom-title">Tech Stack.</div>
          <mark>RESTFUL</mark>
          <mark>Redis</mark>
          <mark>Threading</mark>
          <mark>Python</mark>
          <mark>Django</mark>
      - layout: left-top
        title: 스마트매칭 매칭 알고리즘 개발
        border: weak
        sub_title: Software Developer
        caption: 2021.08 - 2021.11
        description: |
          <div class="custom-title">Description.</div>
          개인화된 스마트매칭 유저 데이터를 바탕으로 프로젝트를 메일링 해주는 서비스입니다.
          기획의 요구에 따라 유저가 저장한 스마트매칭 데이터와 N%일치하고, N개가 일치하는 경우 발송하도록 알고리즘을 설계하고 개발했습니다.
          항목이 추가되고 삭제되는 경우가 많아 확장성있게 설계되었습니다.
          <div class="custom-title">FootPrint.</div>
          - 데이터와 프로젝트 매칭 알고리즘 개발
          - 유저가 외부에서 프로젝트로 바로 접근할 수 있도록 개선
          - 매칭되는 항목이 추가되고 삭제되는 경우가 잦아 확장성 있게 설계됨.
          <div class="custom-title">Tech Stack.</div>
          <mark>Celery</mark>
          <mark>Redis</mark>
          <mark>RESTFUL</mark>
          <mark>Python</mark>
          <mark>Django</mark>

      - layout: left-top
        title: 스마트매칭 도메인 설계 및 개발
        border: weak
        sub_title: Software Developer
        caption: 2020.07 - 2020.10
        description: |
          <div class="custom-title">Description.</div>
          유저가 필요로 하는 프로젝트를 개인화 하고 데이터를 저장하는 것에서 시작한 프로젝트입니다.
          스마트매칭이라는 도메인을 설계 및 개발했습니다.
          데이터를 저장하고 시스템 측면에서 가공하고 처리하는데는 적합했으나, 데이터를 추출하는 측면에선 좋지않았어서 개인적으로 아쉬운 프로젝트였습니다.
          <div class="custom-title">FootPrint.</div>
          - 유저의 개인화된 프로젝트 데이터를 받을 수 있게 페이지 및 로직 개발
          <div class="custom-title">Tech Stack.</div>
          <mark>Python</mark>
          <mark>Django</mark>
          <mark>jQuery</mark>
          <mark>MariaDB</mark>

      - layout: left-top
        title: 평가 도메인 설계 및 개발
        border: weak
        sub_title: Software Developer
        caption: 2020.06 - 2020.10
        description: |
          <div class="custom-title">Description.</div>
          기존 평가가 유효하지 않고, 수집이 잘 되지 않는다는 문제점에서 시작한 프로젝트입니다.
          기존 레거시 대부분 걷어내고, 새로운 평가 도메인을 개발했으며 유저에게 SMS, Mail 발송 로직을 개발하는 테스크를 진행했습니다.
          <div class="custom-title">FootPrint.</div>
          - 평가 항목을 확장하고 비공개 평가를 도입해 평가 신뢰성 개선
          - 외부 채널 안내로(Mail, Kakao) 평가를 유도하고 평가를 확보하도록 개발됨
          - 기존 문제가 있는 레거시를 걷어내 코드 복잡성을 개선
          <div class="custom-title">Tech Stack.</div>
          <mark>Celery</mark>
          <mark>Redis</mark>
          <mark>Python</mark>
          <mark>jQuery</mark>
          <mark>MariaDB</mark>

      - layout: left-top
        title: 위시켓 개발팀 DevOps
        border: weak
        sub_title: Software Developer
        caption: 2019.02 -
        description: |
          <div class="custom-title">Description.</div>
          입사 이후 개발팀 내부에서 DevOps 관련 스크립트 및 툴을 서칭하고 구현했습니다.
          <div class="custom-title">FootPrint.</div>
          - 로컬과 스테이징 서버를 동기화하는 CI/CD를 Github Action으로 구현했습니다.
          - 메인 서버 코드를 배포하는 스크립트를 작성했습니다.
          - Azure를 S3로 이전하는 작업을 진행했습니다.
          <div class="custom-title">Tech Stack.</div>
          <mark>S3</mark>
          <mark>Github Action</mark>
          <mark>Docker</mark>
          <mark>Node.js</mark>

      - layout: left-top
        title: 위시켓 내부 시스템 개선
        sub_title: Software Developer
        caption: 2019.02 -
        description: |
          <div class="custom-title">Description.</div>
          위시켓에서 프로세스 자동화 요청이나 기타 효율 개선을 요청하는 경우 혹은 새로운 도메인이 발생한 경우에
          어드민 기능들을 추가, 개선하고 유지보수를 진행하고 있습니다.
          <div class="custom-title">FootPrint.</div>
          - 유저 관리 어드민 추가
          - 평가 어드민 추가
          - 기존 어드민 NextJS로 전환
          - 기존 레거시 유지보수 등
          <div class="custom-title">Tech Stack.</div>
          <mark>NextJS</mark>
          <mark>Django</mark>
          <mark>RESTFUL</mark>
          <mark>Python</mark>


  - title: Other Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
          border: weak  # Value of `weak` will display a weak border below this item. # Any
          title: 암호화폐 재정거래 프로그램 개선
          sub_title: Software Developer
          caption: 2022.02 - 2022.10
          additional_links:
            - title: ArbitradeTrader
              icon: fab fa-github
              url: https://github.com/songsb13/DiffTrader
          description: | # this will include new lines to allow paragraphs
            <div class="custom-title">Description.</div>
            18년 당시 개발된 재정거래 프로그램의 문제점을 개선하고자 시작한 프로젝트입니다.
            기존에 사용되던 QT, 종속적으로 동작하던 프로그램을 걷어내고, Processing을 통해
            개별적으로 동작하도록 수정했고, 모호한 기능들을 분리하고 정리했습니다.
            <div class="custom-title">FootPrint.</div>
            - 기존 QT 기반 레거시 코드 제거 및 CLI로 변경해 코드 복잡성 개선
            - Threading 기반의 코드에서 Processing으로 변경하여 코드 종속성 개선
            - 모호한 기능을 분리해 명확성 확보 등
            <div class="custom-title">Tech Stack.</div>
            <mark>Python</mark>
            <mark>Redis</mark>
            <mark>Processing</mark>
            <mark>Threading</mark>
            <mark>RESTFUL</mark>
            <mark>Websocket</mark>

        - layout: left
          title: 증권사 API 연동
          sub_title: Software Developer
          border: weak
          caption: 2018.11 - 2019.01
          description: |
            <div class="custom-title">Description.</div>
            외주에서 여러번 요구하던 키움증권과 신한i에 대한 API 모듈을 작성했습니다.
            <div class="custom-title">FootPrint.</div>
            - 신한i에 대한 API 모듈 작성
            - 키움증권에 대한 API 모듈 작성
            <div class="custom-title">Tech Stack.</div>
            <mark>Python</mark>
            <mark>QT</mark>
            <mark>Queue</mark>
            <mark>OpenAPI</mark>
            <mark>Win32</mark>
            <mark>Threading</mark>

        - layout: left
          border: weak
          title: 암호화폐 지표 거래<br/>시스템
          sub_title: Software Developer
          caption: 2018.10 - 2019.01
          description: |
            <div class="custom-title">Description.</div>
            RSI, MACD, Stochastic, CCI 지표를 조합하고 거래를 해보자는 의미에서 시작한 프로젝트입니다.
            API로 연동된 거래소 로직과 지표를 각 오브젝트로 형성하고 후에 and or 조건에 따라 거래 여부를 정하는 방식으로 개발되었습니다.
            이후 암호화폐의 특성상 변동성이 높아 제대로 된 지표를 형성할 수 없다고 판단해 추가 개선은 하지 않았습니다.
            <div class="custom-title">FootPrint.</div>
            - RSI, MACD, Stochastic, CCI에 대한 지표 함수 개발
            - QT로 지표를 조합할 수 있는 GUI 개발
            <div class="custom-title">Tech Stack.</div>
            <mark>Python</mark>
            <mark>QT</mark>
            <mark>Tree</mark>
            <mark>Queue</mark>
            <mark>Threading</mark>

        - layout: left
          title: 암호화폐 재정거래 프로그램 개발
          border: weak
          sub_title: Software Developer
          caption: 2018.04 - 2018.09
          additional_links:
            - title:  ArbitradeTrader
              icon: fab fa-github
              url: https://github.com/songsb13/DiffTrader
          description: | # this will include new lines to allow paragraphs
            <div class="custom-title">Description.</div>
            개발 당시 발생하던 국내외 프리미엄을 이용한 재정거래를 해보자는 의미에서 시작한 프로젝트입니다.
            이전 프로젝트인 "암호화폐 거래소 연동"에서 개발된 함수들을 기반으로 거래소와 요구 차익률등을 입력받고
            시장을 감시하다가 조건을 충족하면 거래하는 형태의 프로그램입니다.
            <div class="custom-title">FootPrint.</div>
            - QT로 현재의 트레이딩 상태 로그, 입력 받는 인풋 등 GUI 위젯 개발
            - 거래소 차익률을 도출하고 비교하는 함수 개발
            <div class="custom-title">Tech Stack.</div>
            <mark>Python</mark>
            <mark>Async</mark>
            <mark>QT</mark>
            <mark>Threading</mark>

        - layout: left
          title: 암호화폐 거래소 API 연동
          sub_title: Software Developer
          caption: 2018.01 - 2018.04
          additional_links:
            - title:  ArbitradeTrader
              icon: fab fa-github
              url: https://github.com/songsb13/DiffTrader
          description: | # this will include new lines to allow paragraphs
            <div class="custom-title">Description.</div>
            국내 거래소인 Bithumb과 Upbit, 국외거래소인 Binance에 대한 API 모듈을 작성했습니다.
            <div class="custom-title">FootPrint.</div>
            - Upbit, Binance, Bithumb API 모듈 개발
            <div class="custom-title">Tech Stack.</div>
            <mark>Python</mark>
            <mark>Redis</mark>
            <mark>Processing</mark>
            <mark>Threading</mark>
            <mark>RESTFUL</mark>
            <mark>Websocket</mark>

  - title: Education
    layout: list
    content:
      - layout: left
        border: weak
        title: 울산과학대학교
        sub_title: Ulsan College
        caption: 2013.02 - 2018.02
        quote: |
          공업전문학사, Associate of Science in Engineering Technology
        description: | # this will include new lines to allow paragraphs
          컴퓨터 정보학을 수료했으며 공업 전문학사 학위를 취득했습니다.
      - layout: left
        title: 학점은행제
        sub_title: The Academic Credit Bank System
        caption: 2018.07 - 2019.02
        quote: |
          공학사, Bachelor of Engineering
        description: |
          3년제 졸업 후 학사 학위를 취득하고자 6개월 가량 학점은행제를 이용했고 컴퓨터 공학을 수료했습니다.



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
