# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

name: Gimo Song
title: Software Developer
email: goodmoskito@gmail.com
phone: 이메일로 문의 부탁 드립니다.
website: https://github.com/songgimo

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  songgimo
linkedin_username: gimosong

about_profile_image: images/gm.jpg


about_title: About Me

about_content: |
    # 안녕하세요, <br> 개발자 송기모입니다. <br>
  


content:
  - title: Summary
    layout: text
    content: | # this will include new lines to allow paragraphs
      서울에서 4년차 개발 엔지니어로 일하고 있으며 백엔드 개발 및 웹개발을 하고 있습니다.
      Python, Django, Linux, AWS, MariaDB, Git 등으로 웹 프로덕션 서비스를 설계 및 개발한 경험과
      외주로부터 Queue, Stack, Tree등의 자료구조를 적용하고 개발한 경험이 있습니다. <br>
      
      코드의 확장과 유지보수가 수월한 백엔드 구조와 패턴에 대해 고민하고, 개발하고자 하며
      대부분의 프로젝트에서 기획 단계부터 릴리즈까지의 단계에 참여해 제품 개발 사이클에 대한 이해가 있습니다.

      서비스 개발은 비단 코드를 잘 짜는 것 뿐만 아닌 기획과 도메인의 목적에 맞는 코드를 설계하고 개발해야 한다고 믿습니다.<br>
      그렇기에 더 좋은 개발자로서 발전하기 위해 적극적인 커뮤니케이션으로 기획과 목적을 오해없이 동기화하고 코드에 녹여내고자 노력하고 있습니다.
      
  - title: Skill Highlights
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Python
      - Django
      - Git
      - AWS EC2, RDS, OpenSearch
      - MySQL, MariaDB
      - NextJS
      - Redis
      - Celery
      - Threading, MultiProcessing
      - HTML, jQuery, SCSS 등

  - title: Work Experience
    layout: list
    content:
      - layout: left-top
        title: 위시켓
        sub_title: Software Developer
        caption: 2019.02 -
        link: wishket.com
        description: | # this will include new lines to allow paragraphs Description of role
          - 내부 어드민 개선 및 레거시 제거
          - 사용자가 요구하는 MVP 개발
          - 기존 비즈니스 로직에 대한 유지보수
          - 개발팀 DevOps 구축 및 개선
          - 내부 도메인 서비스 개선
          - 리뷰 MVP 설계 및 개발
          - 스마트매칭 MVP 설계 및 개발
          - 요즘IT 검색 알고리즘 개선
          - 스마트매칭 매칭 알고리즘 개발
          - 사용 스킬셋
            - Python, Django, jQuery, NextJS, Redis, Celery, RESTFUL, MariaDB
  - title: Other Experience
    layout: list
    content:
      - layout: left-top
        border: weak
        title: 프리랜서 활동
        sub_title: Software Developer
        caption: 2017.02 - 2019.01
        description: | # 
          - 업비트 알고리즘 거래 시스템 개발
          - 키움증권 시세추종 MVP 개발
          - DB운용 서비스 개발 및 유지보수
          - 기타 데이터 수집 자동화 앱 개발
          - Python, JavaScript, MySQL, MongoDB, SQLite, PHP, RESTFUL, QT, Selenium
          <br><br>
      - layout: left-top
        border: weak
        title: 팀 프로젝트 활동
        sub_title: Software Developer
        caption: 2017.02 -
        description: | # 
          - 업비트, 빗썸, 바이낸스 3개 거래소 API, Websocket 연동
          - 거래소 간 코인 가격 차이를 이용한 재정거래 시스템 개발
          - MSI, CCI, Stochastic 등 N개의 보조지표를 조합하고 거래하는 시스템 개발
          - 키움증권 알고리즘 거래 시스템 개발
          - Python, MySQL, Flask, QT, Threading, Processing
      - layout: left-top
        title: 사이버사령부
        sub_title: 정보보호병
        caption: 2015.07 - 2017.02
        description: | #
          - 서버 관리 및 운영
          - 암호 변경 스크립트 및 서버 상태 확인 스크립트 등 작성
  - title: Projects
    layout: list
    border: weak
    content:
      - layout: left-top
        title: 위시켓 내부 시스템 개선
        sub_title: Software Developer
        caption: 2019.02 -
        description: |
          위시켓에서 프로세스 자동화 요청이나 기타 효율 개선을 요청하는 경우 혹은 새로운 도메인이 발생한 경우에
          어드민 기능들을 추가, 개선하고 유지보수를 진행하고 있습니다.
          <br>
          - 유저 관리 어드민 추가
          - 평가 어드민 추가
          - 기존 어드민 NextJS로 전환
          - 기존 레거시 유지보수 등

      - layout: left-top
        title: 요즘IT 검색 알고리즘 개선
        border: weak
        sub_title: Software Developer
        caption: 2022.08 - 2022.10
        description: |
          요즘IT의 검색기능이 제한적이고 정확한 컨텐츠를 검색하지 못하는 배경에서 시작한 프로젝트입니다.
          AWS OpenSearch의 서버를 구축하고 위시켓DB를 연동했으며 검색 알고리즘을 설계하고 개발했습니다.
          속도 및 정확도가 개선되었고, 기획에서 요구하던 특정 문자열을 Split하여 검색어 조합이 가능하게 했습니다.
          
          - RESTFUL, Redis, Celery, OpenSearch 등

      - layout: left-top
        title: 요즘IT 슬랙봇 구독 서비스 설계 및 개발
        border: weak
        sub_title: Software Developer
        caption: 2022.05 - 2022.08
        description: |
          슬랙봇 구독 서비스를 통해 유저에게 발행된 컨텐츠를 바로 안내하고 페이지로 후킹하기 위해 시작된 프로젝트입니다.
          슬랙 Message API로 슬랙과 연동했고, Threading, Redis를 이용해 오버헤드 없이 컨텐츠를 받아볼 수 있게 처리했습니다.
          - RESTFUL, Redis, Threading, Python, Django 등
      - layout: left-top
        title: 스마트매칭 매칭 알고리즘 개발
        border: weak
        sub_title: Software Developer
        caption: 2021.08 - 2021.11
        description: |
          개인화된 스마트매칭 유저 데이터를 바탕으로 프로젝트를 메일링 해주는 서비스입니다.
          기획의 요구에 따라 유저가 저장한 스마트매칭 데이터와 N%일치하고, N개가 일치하는 경우 발송하도록 알고리즘을 설계하고 개발했습니다.
          항목이 추가되고 삭제되는 경우가 많아 확장성있게 설계되었습니다.
          - Celery, Redis, RESTFUL, Python, Django 등

      - layout: left-top
        title: 스마트매칭 도메인 설계 및 개발
        border: weak
        sub_title: Software Developer
        caption: 2020.07 - 2020.10
        description: |
          유저가 필요로 하는 프로젝트를 개인화 하고 데이터를 저장하는 것에서 시작한 프로젝트입니다.
          스마트매칭이라는 페이지의 MVP를 설계 및 개발했습니다.
          데이터를 저장하고 시스템 측면에서 가공하고 처리하는데는 적합했으나, 데이터를 추출하는 측면에선 좋지않았어서 개인적으로 아쉬운 프로젝트였습니다.
          - Python, Django, jQuery, MariaDB 등

      - layout: left-top
        title: 평가 도메인 설계 및 개발
        border: weak
        sub_title: Software Developer
        caption: 2020.06 - 2020.10
        description: |
          기존 평가가 유효하지 않고, 수집이 잘 되지 않는다는 문제점에서 시작한 프로젝트입니다.
          기존 레거시 대부분 걷어내고, 새로운 평가 MVP를 개발했으며 유저에게 SMS, Mail 발송 로직을 개발하는 테스크를 진행했습니다.
          - Celery, Redis, Python, jQuery, MariaDB 등

      - layout: left-top
        title: 위시켓 개발팀 DevOps
        border: weak
        sub_title: Software Developer
        caption: 2020.03 -
        description: |
          - 로컬과 스테이징 서버를 동기화하는 CI/CD를 Github Action으로 구현했습니다.
          - 메인 서버 코드를 배포하는 스크립트를 작성했습니다.
          - Azure를 S3로 이전하는 작업을 진행했습니다.

  - title: Other Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
          border: weak  # Value of `weak` will display a weak border below this item. # Any
          title: 암호화폐 재정거래 프로그램 개선
          sub_title: Software Developer
          caption: 2022.02 - 2022.10
          additional_links:
            - title: ArbitradeTrader
              icon: fab fa-github
              url: https://github.com/songsb13/DiffTrader
          description: | # this will include new lines to allow paragraphs
            18년 당시 개발된 재정거래 프로그램의 문제점을 개선하고자 시작한 프로젝트입니다.
            기존에 사용되던 QT, 종속적으로 동작하던 프로그램을 걷어내고, Processing을 통해
            개별적으로 동작하도록 수정했고, 모호한 기능들을 분리하고 정리했습니다.
            - Python, Redis, Processing, Threading, RESTFUL, Websocket

        - layout: left
          title: 키움증권 알고리즘 거래<br/>시스템
          sub_title: Software Developer
          caption: 2018.11 - 2019.01
          description: |
            - 

        - layout: left
          border: weak
          title: 암호화폐 보조지표 거래<br/>시스템
          sub_title: Software Developer
          caption: 2018.10 - 2019.01
          description: |
            RSI, MACD, Stochastic, CCI 보조지표를 조합하고 거래를 해보자는 의미에서 시작한 프로젝트입니다.
            API로 연동된 거래소 로직과 보조지표를 각 오브젝트로 형성하고 후에 and or 조건에 따라 거래 여부를 정하는 방식으로 개발되었습니다.
            이후 암호화폐의 특성상 변동성이 높아 제대로 된 보조지표를 형성할 수 없다고 판단해 추가 개선은 하지 않았습니다.
            Python, QT, Tree, Queue, Threading 등

        - layout: left
          title: 암호화폐 재정거래 프로그램 개발
          sub_title: Software Developer
          caption: 2018.04 - 2018.09
          additional_links:
            - title:  ArbitradeTrader
              icon: fab fa-github
              url: https://github.com/songsb13/DiffTrader
          description: | # this will include new lines to allow paragraphs
            개발 당시 발생하던 국내외 프리미엄을 이용한 재정거래를 해보자는 의미에서 시작한 프로젝트입니다.
            국내 거래소인 Bithumb, Upbit와 국외 거래소인 Binance에 대한 통신 함수를 작성했고
            입력한 2개의 거래소의 차익이 n%를 초과하면 자동으로 거래가 되도록 개발했습니다.
            
            - Python, Redis, Processing, Threading, RESTFUL, Websocket

        - layout: left
          title: 암호화폐 거래소 연동 (Upbit, Binance, Bithumb)
          sub_title: Software Developer
          caption: 2018.01 - 2018.04
          additional_links:
            - title:  ArbitradeTrader
              icon: fab fa-github
              url: https://github.com/songsb13/DiffTrader
          description: | # this will include new lines to allow paragraphs
            개발 당시 발생하던 국내외 프리미엄을 이용한 재정거래를 해보자는 의미에서 시작한 프로젝트입니다.
            국내 거래소인 Bithumb, Upbit와 국외 거래소인 Binance에 대한 통신 함수를 작성했고
            입력한 2개의 거래소의 차익이 n%를 초과하면 자동으로 거래가 되도록 개발했습니다.
            
            - Python, Redis, Processing, Threading, RESTFUL, Websocket

  - title: Education
    layout: list
    content:
      - layout: left
        title: 울산과학대학교
        sub_title: Ulsan College
        caption: 2013.02 - 2018.02
        quote: |
          공업전문학사, Associate of Science in Engineering Technology
        description: | # this will include new lines to allow paragraphs
          컴퓨터 정보학을 수료했으며 공업 전문학사 학위를 취득했습니다.
      - layout: left
        title: 학점은행제
        sub_title: The Academic Credit Bank System
        caption: 2018.07 - 2019.02
        quote: |
          공학사, Bachelor of Engineering
        description: |
          3년제 졸업 후 학사 학위를 취득하고자 6개월 가량 학점은행제를 이용했고 컴퓨터 공학을 수료했습니다.



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
